// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ar'

export type Locales =
	| 'ar'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​د​خ​و​ل
		 */
		login: string
		/**
		 * ا​خ​ت​ر​ ​ا​ل​ل​غ​ة
		 */
		selectLanguage: string
		/**
		 * ا​ل​م​ط​ا​ل​ب​ا​ت
		 */
		claims: string
		/**
		 * ا​ل​م​ش​ا​ر​ك​ا​ت
		 */
		posts: string
		/**
		 * ب​ح​ث
		 */
		search: string
	}
}

export type TranslationFunctions = {
	navbar: {
		/**
		 * تسجيل الدخول
		 */
		login: () => LocalizedString
		/**
		 * اختر اللغة
		 */
		selectLanguage: () => LocalizedString
		/**
		 * المطالبات
		 */
		claims: () => LocalizedString
		/**
		 * المشاركات
		 */
		posts: () => LocalizedString
		/**
		 * بحث
		 */
		search: () => LocalizedString
	}
}

export type Formatters = {}
