// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ar'

export type Locales =
	| 'ar'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * ا​ي​ت​م​ز
	 */
	title: string
	/**
	 * ا​ي​ت​م​ز​ ​ه​ي​ ​م​ن​ص​ة​ ​ت​س​ه​ل​ ​ا​ي​ج​ا​د​ ​ا​ش​ي​ا​ء​ ​م​ف​ق​و​د​ة
	 */
	intro: string
	/**
	 * ا​ب​د​ا​ ​ا​ل​ا​ن
	 */
	startNow: string
}

export type TranslationFunctions = {
	/**
	 * ايتمز
	 */
	title: () => LocalizedString
	/**
	 * ايتمز هي منصة تسهل ايجاد اشياء مفقودة
	 */
	intro: () => LocalizedString
	/**
	 * ابدا الان
	 */
	startNow: () => LocalizedString
}

export type Formatters = {}
