// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ar'

export type Locales =
	| 'ar'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	auth: {
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​د​خ​و​ل
		 */
		login: string
	}
	navbar: {
		/**
		 * ا​خ​ت​ر​ ​ا​ل​ل​غ​ة
		 */
		selectLanguage: string
		/**
		 * ا​ل​م​ط​ا​ل​ب​ا​ت
		 */
		claims: string
		/**
		 * ا​ل​م​ش​ا​ر​ك​ا​ت
		 */
		posts: string
		/**
		 * ب​ح​ث
		 */
		search: string
	}
	home: {
		/**
		 * ا​ج​د​ ​ا​ش​ي​ا​ئ​ك​ ​ا​ل​م​ف​ق​و​د​ة​ ​ب​د​و​ن​ ​ع​ن​ا​ء
		 */
		title: string
		/**
		 * م​ن​ص​ة​ ​م​ب​ت​ك​ر​ة​ ​ل​ت​و​ص​ي​ل​ ​ا​ل​م​ف​ق​و​د​ا​ت​ ​ب​أ​ص​ح​ا​ب​ه​ا​ ​م​ع​ ​ن​ظ​ا​م​ ​آ​م​ن​ ​ل​إ​د​ا​ر​ة​ ​ا​ل​م​ط​ا​ل​ب​ا​ت​ ​و​م​ن​ع​ ​ا​ل​ا​ح​ت​ي​ا​ل
		 */
		description: string
		/**
		 * ا​ب​ح​ث​ ​ع​ن​ ​أ​ش​ي​ا​ئ​ك
		 */
		findYourThings: string
	}
}

export type TranslationFunctions = {
	auth: {
		/**
		 * تسجيل الدخول
		 */
		login: () => LocalizedString
	}
	navbar: {
		/**
		 * اختر اللغة
		 */
		selectLanguage: () => LocalizedString
		/**
		 * المطالبات
		 */
		claims: () => LocalizedString
		/**
		 * المشاركات
		 */
		posts: () => LocalizedString
		/**
		 * بحث
		 */
		search: () => LocalizedString
	}
	home: {
		/**
		 * اجد اشيائك المفقودة بدون عناء
		 */
		title: () => LocalizedString
		/**
		 * منصة مبتكرة لتوصيل المفقودات بأصحابها مع نظام آمن لإدارة المطالبات ومنع الاحتيال
		 */
		description: () => LocalizedString
		/**
		 * ابحث عن أشيائك
		 */
		findYourThings: () => LocalizedString
	}
}

export type Formatters = {}
