// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ar'

export type Locales =
	| 'ar'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * ت​أ​ك​ي​د
		 */
		confirm: string
		/**
		 * إ​ل​غ​ا​ء
		 */
		cancel: string
		/**
		 * ن​ج​ا​ح
		 */
		success: string
		/**
		 * خ​ط​أ
		 */
		error: string
		/**
		 * م​ع​ل​و​م​ا​ت
		 */
		info: string
	}
	validation: {
		/**
		 * ا​ل​ا​س​م​ ​ا​ل​ك​ا​م​ل​ ​ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل​ ​6​ ​أ​ح​ر​ف
		 */
		fullname: string
		/**
		 * ع​ن​و​ا​ن​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​غ​ي​ر​ ​ص​ا​ل​ح
		 */
		email: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ك​و​ن​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​م​ك​و​ن​ة​ ​م​ن​ ​8​ ​أ​ح​ر​ف​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordLength: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​خ​ا​ص​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordSpecialChar: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ر​ق​م​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordNumber: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​ك​ب​ي​ر​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordUppercase: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​ص​غ​ي​ر​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordLowercase: string
	}
	auth: {
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​د​خ​و​ل
		 */
		login: string
		/**
		 * إ​ن​ش​ا​ء​ ​ح​س​ا​ب
		 */
		signup: string
		/**
		 * ا​ل​ا​س​م​ ​ا​ل​ك​ا​م​ل
		 */
		fullname: string
		/**
		 * ا​ل​ب​ر​ي​د​ ​ا​ل​ا​ل​ك​ت​ر​و​ن​ي
		 */
		email: string
		/**
		 * ك​ل​م​ة​ ​ا​ل​م​ر​و​ر
		 */
		password: string
		/**
		 * ل​د​ي​ك​ ​ح​س​ا​ب​ ​ب​ا​ل​ف​ع​ل​؟
		 */
		alreadyHaveAccount: string
		/**
		 * ل​ي​س​ ​ل​د​ي​ك​ ​ح​س​ا​ب​؟
		 */
		dontHaveAccount: string
		/**
		 * ن​س​ي​ت​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​؟
		 */
		forgetPassword: string
		/**
		 * إ​ر​س​ا​ل​ ​ا​ل​ر​م​ز
		 */
		sendTheCode: string
		/**
		 * إ​ع​ا​د​ة​ ​إ​ر​س​ا​ل​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي
		 */
		resendEmail: string
		/**
		 * ت​م​ ​إ​ع​ا​د​ة​ ​إ​ر​س​ا​ل​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​ب​ن​ج​ا​ح
		 */
		resendSuccess: string
		/**
		 * ت​م​ ​إ​ر​س​ا​ل​ ​ا​ل​ر​م​ز​ ​ب​ن​ج​ا​ح
		 */
		sendSuccess: string
		/**
		 * ا​ل​ر​م​ز​ ​ص​ح​ي​ح
		 */
		validCode: string
		/**
		 * ت​ح​ق​ق​ ​م​ن​ ​ا​ل​ر​م​ز
		 */
		verifyCode: string
		/**
		 * ا​ك​ت​ب​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​ا​ل​ذ​ي​ ​ن​س​ي​ت​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​خ​ا​ص​ة​ ​ب​ه
		 */
		lostPasswordEmail: string
		/**
		 * ل​ق​د​ ​أ​ر​س​ل​ن​ا​ ​ل​ك​ ​ك​ل​م​ة​ ​م​ر​و​ر​ ​ل​م​ر​ة​ ​و​ا​ح​د​ة​؛​ ​ت​ح​ق​ق​ ​م​ن​ ​ص​ن​د​و​ق​ ​ا​ل​و​ا​ر​د​ ​ف​ي​ ​ب​ر​ي​د​ك​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​.​ ​ث​م​ ​ا​ك​ت​ب​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​ج​د​ي​د​ة​.
		 */
		resetPassword: string
		/**
		 * ت​أ​ك​ي​د​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​ج​د​ي​د​ة
		 */
		confirmNewPassword: string
		/**
		 * ل​ق​د​ ​أ​ر​س​ل​ن​ا​ ​ل​ك​ ​ك​ل​م​ة​ ​م​ر​و​ر​ ​ل​ل​ت​ح​ق​ق​ ​م​ن​ ​ب​ر​ي​د​ك​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​.​ ​ت​ح​ق​ق​ ​م​ن​ ​ص​ن​د​و​ق​ ​ا​ل​و​ا​ر​د​ ​ا​ل​خ​ا​ص​ ​ب​ك​؛​ ​إ​ذ​ا​ ​ل​م​ ​ي​ك​ن​ ​م​و​ج​و​د​ً​ا​،​ ​ت​ح​ق​ق​ ​م​ن​ ​م​ج​ل​د​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​ع​ش​و​ا​ئ​ي
		 */
		verificationEmail: string
		/**
		 * ي​ب​د​و​ ​أ​ن​ ​ه​ذ​ا​ ​ا​ل​ح​س​ا​ب​ ​م​و​ج​و​د​ ​ب​ا​ل​ف​ع​ل
		 */
		acounntAlreadyExist: string
		/**
		 * ي​ب​د​و​ ​أ​ن​ ​ه​ذ​ا​ ​ا​ل​ح​س​ا​ب​ ​غ​ي​ر​ ​م​و​ج​و​د
		 */
		accountDoesNotExist: string
		/**
		 * ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​غ​ي​ر​ ​ص​ح​ي​ح​ة
		 */
		passwordIncorrect: string
		/**
		 * ا​ل​ر​م​ز​ ​غ​ي​ر​ ​ص​ح​ي​ح
		 */
		incorrectCode: string
		/**
		 * ا​ل​ر​م​ز​ ​م​ن​ت​ه​ي​ ​ا​ل​ص​ل​ا​ح​ي​ة​،​ ​ح​ا​و​ل​ ​إ​ع​ا​د​ة​ ​ا​ل​إ​ر​س​ا​ل
		 */
		expiredCode: string
	}
	navbar: {
		/**
		 * ا​خ​ت​ر​ ​ا​ل​ل​غ​ة
		 */
		selectLanguage: string
		/**
		 * ا​ل​م​ط​ا​ل​ب​ا​ت
		 */
		claims: string
		/**
		 * ا​ل​م​ش​ا​ر​ك​ا​ت
		 */
		posts: string
		/**
		 * ب​ح​ث
		 */
		search: string
	}
	home: {
		/**
		 * ا​ج​د​ ​ا​ش​ي​ا​ئ​ك​ ​ا​ل​م​ف​ق​و​د​ة​ ​ب​د​و​ن​ ​ع​ن​ا​ء
		 */
		title: string
		/**
		 * م​ن​ص​ة​ ​م​ب​ت​ك​ر​ة​ ​ل​ت​و​ص​ي​ل​ ​ا​ل​م​ف​ق​و​د​ا​ت​ ​ب​أ​ص​ح​ا​ب​ه​ا​ ​م​ع​ ​ن​ظ​ا​م​ ​آ​م​ن​ ​ل​إ​د​ا​ر​ة​ ​ا​ل​م​ط​ا​ل​ب​ا​ت​ ​و​م​ن​ع​ ​ا​ل​ا​ح​ت​ي​ا​ل
		 */
		description: string
		/**
		 * ا​ب​ح​ث​ ​ع​ن​ ​أ​ش​ي​ا​ئ​ك
		 */
		findYourThings: string
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * تأكيد
		 */
		confirm: () => LocalizedString
		/**
		 * إلغاء
		 */
		cancel: () => LocalizedString
		/**
		 * نجاح
		 */
		success: () => LocalizedString
		/**
		 * خطأ
		 */
		error: () => LocalizedString
		/**
		 * معلومات
		 */
		info: () => LocalizedString
	}
	validation: {
		/**
		 * الاسم الكامل يجب أن يكون على الأقل 6 أحرف
		 */
		fullname: () => LocalizedString
		/**
		 * عنوان البريد الإلكتروني غير صالح
		 */
		email: () => LocalizedString
		/**
		 * يجب أن تكون كلمة المرور مكونة من 8 أحرف على الأقل
		 */
		passwordLength: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف خاص واحد على الأقل
		 */
		passwordSpecialChar: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على رقم واحد على الأقل
		 */
		passwordNumber: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل
		 */
		passwordUppercase: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل
		 */
		passwordLowercase: () => LocalizedString
	}
	auth: {
		/**
		 * تسجيل الدخول
		 */
		login: () => LocalizedString
		/**
		 * إنشاء حساب
		 */
		signup: () => LocalizedString
		/**
		 * الاسم الكامل
		 */
		fullname: () => LocalizedString
		/**
		 * البريد الالكتروني
		 */
		email: () => LocalizedString
		/**
		 * كلمة المرور
		 */
		password: () => LocalizedString
		/**
		 * لديك حساب بالفعل؟
		 */
		alreadyHaveAccount: () => LocalizedString
		/**
		 * ليس لديك حساب؟
		 */
		dontHaveAccount: () => LocalizedString
		/**
		 * نسيت كلمة المرور؟
		 */
		forgetPassword: () => LocalizedString
		/**
		 * إرسال الرمز
		 */
		sendTheCode: () => LocalizedString
		/**
		 * إعادة إرسال البريد الإلكتروني
		 */
		resendEmail: () => LocalizedString
		/**
		 * تم إعادة إرسال البريد الإلكتروني بنجاح
		 */
		resendSuccess: () => LocalizedString
		/**
		 * تم إرسال الرمز بنجاح
		 */
		sendSuccess: () => LocalizedString
		/**
		 * الرمز صحيح
		 */
		validCode: () => LocalizedString
		/**
		 * تحقق من الرمز
		 */
		verifyCode: () => LocalizedString
		/**
		 * اكتب البريد الإلكتروني الذي نسيت كلمة المرور الخاصة به
		 */
		lostPasswordEmail: () => LocalizedString
		/**
		 * لقد أرسلنا لك كلمة مرور لمرة واحدة؛ تحقق من صندوق الوارد في بريدك الإلكتروني. ثم اكتب كلمة المرور الجديدة.
		 */
		resetPassword: () => LocalizedString
		/**
		 * تأكيد كلمة المرور الجديدة
		 */
		confirmNewPassword: () => LocalizedString
		/**
		 * لقد أرسلنا لك كلمة مرور للتحقق من بريدك الإلكتروني. تحقق من صندوق الوارد الخاص بك؛ إذا لم يكن موجودًا، تحقق من مجلد البريد العشوائي
		 */
		verificationEmail: () => LocalizedString
		/**
		 * يبدو أن هذا الحساب موجود بالفعل
		 */
		acounntAlreadyExist: () => LocalizedString
		/**
		 * يبدو أن هذا الحساب غير موجود
		 */
		accountDoesNotExist: () => LocalizedString
		/**
		 * كلمة المرور غير صحيحة
		 */
		passwordIncorrect: () => LocalizedString
		/**
		 * الرمز غير صحيح
		 */
		incorrectCode: () => LocalizedString
		/**
		 * الرمز منتهي الصلاحية، حاول إعادة الإرسال
		 */
		expiredCode: () => LocalizedString
	}
	navbar: {
		/**
		 * اختر اللغة
		 */
		selectLanguage: () => LocalizedString
		/**
		 * المطالبات
		 */
		claims: () => LocalizedString
		/**
		 * المشاركات
		 */
		posts: () => LocalizedString
		/**
		 * بحث
		 */
		search: () => LocalizedString
	}
	home: {
		/**
		 * اجد اشيائك المفقودة بدون عناء
		 */
		title: () => LocalizedString
		/**
		 * منصة مبتكرة لتوصيل المفقودات بأصحابها مع نظام آمن لإدارة المطالبات ومنع الاحتيال
		 */
		description: () => LocalizedString
		/**
		 * ابحث عن أشيائك
		 */
		findYourThings: () => LocalizedString
	}
}

export type Formatters = {}
