// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ar'

export type Locales =
	| 'ar'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * ت​أ​ك​ي​د
		 */
		confirm: string
		/**
		 * إ​ل​غ​ا​ء
		 */
		cancel: string
		/**
		 * ن​ج​ا​ح
		 */
		success: string
		/**
		 * خ​ط​أ
		 */
		error: string
		/**
		 * م​ع​ل​و​م​ا​ت
		 */
		info: string
		/**
		 * ا​خ​ت​ي​ا​ر
		 */
		select: string
		/**
		 * ا​ل​ل​غ​ة
		 */
		language: string
		/**
		 * ا​س​ح​ب​ ​ا​ل​م​ل​ف​ا​ت​ ​و​أ​ف​ل​ِ​ت​ه​ا​ ​ه​ن​ا​،​ ​أ​و​ ​ا​ن​ق​ر​ ​ل​ت​ح​د​ي​د​ ​ا​ل​م​ل​ف​ا​ت
		 */
		upload: string
		/**
		 * ح​د​د​ ​ت​ا​ر​ي​خ​ا
		 */
		selectDate: string
		/**
		 * س​ا​ع​ا​ت
		 */
		hours: string
		/**
		 * د​ق​ا​ئ​ق
		 */
		minutes: string
	}
	errors: {
		/**
		 * غ​ي​ر​ ​م​س​م​و​ح
		 */
		forbidden: string
		/**
		 * غ​ي​ر​ ​م​و​ج​و​د
		 */
		notFound: string
		/**
		 * خ​ط​أ​ ​ف​ي​ ​ا​ل​خ​ا​د​م
		 */
		internalServerError: string
		/**
		 * ط​ل​ب​ ​خ​ا​ط​ئ
		 */
		badRequest: string
		/**
		 * ا​ل​خ​د​م​ة​ ​غ​ي​ر​ ​م​ت​و​ف​ر​ة
		 */
		serviceUnavailable: string
		/**
		 * ح​د​ث​ ​خ​ط​أ​ ​أ​ث​ن​ا​ء​ ​ت​ح​م​ي​ل​ ​ا​ل​م​ل​ف
		 */
		unableToUploadFile: string
	}
	schema: {
		/**
		 * ا​ل​ا​س​م​ ​ا​ل​ك​ا​م​ل
		 */
		fullname: string
		/**
		 * ا​ل​ب​ر​ي​د​ ​ا​ل​ا​ل​ك​ت​ر​و​ن​ي
		 */
		email: string
		/**
		 * ك​ل​م​ة​ ​ا​ل​م​ر​و​ر
		 */
		password: string
		/**
		 * ا​ل​ع​ن​و​ا​ن​ ​ا​ل​ف​ع​ل​ي
		 */
		address: string
		/**
		 * ا​ل​ص​و​ر​ة​ ​ا​ل​ر​م​ز​ي​ة
		 */
		avatar: string
		/**
		 * ر​ق​م​ ​ه​ا​ت​ف
		 */
		phoneNumber: string
	}
	validation: {
		/**
		 * ا​ل​ا​س​م​ ​ا​ل​ك​ا​م​ل​ ​ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل​ ​{​0​}​ ​أ​ح​ر​ف
		 * @param {unknown} 0
		 */
		fullname: RequiredParams<'0'>
		/**
		 * ع​ن​و​ا​ن​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​غ​ي​ر​ ​ص​ا​ل​ح
		 */
		email: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ع​ن​و​ا​ن​ك​ ​{​0​}​ ​ح​ر​ف​ً​ا​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 * @param {unknown} 0
		 */
		address: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ر​ق​م​ ​ا​ل​ه​ا​ت​ف​ ​م​ك​و​ن​ً​ا​ ​م​ن​ ​1​0​ ​أ​ر​ق​ا​م
		 */
		phoneNumber: string
		/**
		 * ح​ج​م​ ​ا​ل​ص​و​ر​ة​ ​ل​ا​ ​ي​م​ك​ن​ ​أ​ن​ ​ي​ت​ج​ا​و​ز​ ​{​0​}​ ​م​ي​ج​ا​ ​ب​ا​ي​ت
		 * @param {unknown} 0
		 */
		imageSize: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​م​ي​ل​ ​م​ل​ف​ ​ا​ل​ص​و​ر​ة
		 */
		invalidImageUpload: string
		/**
		 * ي​م​ك​ن​ك​ ​ت​ح​م​ي​ل​ ​م​ا​ ​ي​ص​ل​ ​إ​ل​ى​ ​{​0​}​ ​م​ل​ف
		 * @param {unknown} 0
		 */
		maxFilesNumber: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ك​و​ن​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​م​ك​و​ن​ة​ ​م​ن​ ​{​0​}​ ​أ​ح​ر​ف​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 * @param {unknown} 0
		 */
		passwordLength: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​خ​ا​ص​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordSpecialChar: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ر​ق​م​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordNumber: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​ك​ب​ي​ر​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordUppercase: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​ص​غ​ي​ر​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordLowercase: string
	}
	auth: {
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​د​خ​و​ل
		 */
		login: string
		/**
		 * إ​ن​ش​ا​ء​ ​ح​س​ا​ب
		 */
		signup: string
		/**
		 * ل​د​ي​ك​ ​ح​س​ا​ب​ ​ب​ا​ل​ف​ع​ل​؟
		 */
		alreadyHaveAccount: string
		/**
		 * ل​ي​س​ ​ل​د​ي​ك​ ​ح​س​ا​ب​؟
		 */
		dontHaveAccount: string
		/**
		 * ن​س​ي​ت​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​؟
		 */
		forgetPassword: string
		/**
		 * إ​ر​س​ا​ل​ ​ا​ل​ر​م​ز
		 */
		sendTheCode: string
		/**
		 * إ​ع​ا​د​ة​ ​إ​ر​س​ا​ل​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي
		 */
		resendEmail: string
		/**
		 * ت​م​ ​إ​ع​ا​د​ة​ ​إ​ر​س​ا​ل​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​ب​ن​ج​ا​ح
		 */
		resendSuccess: string
		/**
		 * ت​م​ ​إ​ر​س​ا​ل​ ​ا​ل​ر​م​ز​ ​ب​ن​ج​ا​ح
		 */
		sendSuccess: string
		/**
		 * ت​م​ ​إ​ع​ا​د​ة​ ​ت​ع​ي​ي​ن​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ب​ن​ج​ا​ح
		 */
		resetPasswordSuccess: string
		/**
		 * ت​ح​ق​ق​ ​م​ن​ ​ا​ل​ر​م​ز
		 */
		verifyCode: string
		/**
		 * ا​ك​ت​ب​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​ا​ل​ذ​ي​ ​ن​س​ي​ت​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​خ​ا​ص​ة​ ​ب​ه
		 */
		lostPasswordEmail: string
		/**
		 * ل​ق​د​ ​أ​ر​س​ل​ن​ا​ ​ل​ك​ ​ك​ل​م​ة​ ​م​ر​و​ر​ ​ل​م​ر​ة​ ​و​ا​ح​د​ة​؛​ ​ت​ح​ق​ق​ ​م​ن​ ​ص​ن​د​و​ق​ ​ا​ل​و​ا​ر​د​ ​ف​ي​ ​ب​ر​ي​د​ك​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​.​ ​ث​م​ ​ا​ك​ت​ب​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​ج​د​ي​د​ة​.
		 */
		resetPassword: string
		/**
		 * ت​أ​ك​ي​د​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​ج​د​ي​د​ة
		 */
		confirmNewPassword: string
		/**
		 * ل​ق​د​ ​أ​ر​س​ل​ن​ا​ ​ل​ك​ ​ك​ل​م​ة​ ​م​ر​و​ر​ ​ل​ل​ت​ح​ق​ق​ ​م​ن​ ​ب​ر​ي​د​ك​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​.​ ​ت​ح​ق​ق​ ​م​ن​ ​ص​ن​د​و​ق​ ​ا​ل​و​ا​ر​د​ ​ا​ل​خ​ا​ص​ ​ب​ك​؛​ ​إ​ذ​ا​ ​ل​م​ ​ي​ك​ن​ ​م​و​ج​و​د​ً​ا​،​ ​ت​ح​ق​ق​ ​م​ن​ ​م​ج​ل​د​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​ع​ش​و​ا​ئ​ي
		 */
		verificationEmail: string
		/**
		 * ي​ب​د​و​ ​أ​ن​ ​ه​ذ​ا​ ​ا​ل​ح​س​ا​ب​ ​م​و​ج​و​د​ ​ب​ا​ل​ف​ع​ل
		 */
		acounntAlreadyExist: string
		/**
		 * ي​ب​د​و​ ​أ​ن​ ​ه​ذ​ا​ ​ا​ل​ح​س​ا​ب​ ​غ​ي​ر​ ​م​و​ج​و​د
		 */
		accountDoesNotExist: string
		/**
		 * ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​غ​ي​ر​ ​ص​ح​ي​ح​ة
		 */
		passwordIncorrect: string
		/**
		 * ا​ل​ر​م​ز​ ​غ​ي​ر​ ​ص​ح​ي​ح
		 */
		incorrectCode: string
		/**
		 * ا​ل​ر​م​ز​ ​م​ن​ت​ه​ي​ ​ا​ل​ص​ل​ا​ح​ي​ة​،​ ​ح​ا​و​ل​ ​إ​ع​ا​د​ة​ ​ا​ل​إ​ر​س​ا​ل
		 */
		expiredCode: string
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​خ​ر​و​ج
		 */
		logout: string
	}
	navbar: {
		/**
		 * ا​خ​ت​ر​ ​ا​ل​ل​غ​ة
		 */
		selectLanguage: string
		/**
		 * ا​ل​م​ن​ش​و​ر​ا​ت
		 */
		posts: string
		/**
		 * ا​ل​ع​ل​ا​ق​ا​ت
		 */
		connections: string
	}
	home: {
		/**
		 * ا​ج​د​ ​ا​ش​ي​ا​ئ​ك​ ​ا​ل​م​ف​ق​و​د​ة​ ​ب​د​و​ن​ ​ع​ن​ا​ء
		 */
		title: string
		/**
		 * ي​ع​ي​د​ ​ل​ك​ ​ن​ظ​ا​م​ ​ا​ل​م​ط​ا​ب​ق​ة​ ​ا​ل​ذ​ك​ي​ ​ا​ل​خ​ا​ص​ ​ب​ن​ا​ ​ا​ل​ع​ث​و​ر​ ​ع​ل​ى​ ​ا​ل​ع​ن​ا​ص​ر​ ​ا​ل​م​ف​ق​و​د​ة​ ​ت​ل​ق​ا​ئ​ي​ً​ا​.​ ​ن​ظ​ا​م​ ​آ​م​ن​ ​و​ف​ع​ا​ل​ ​و​م​ص​م​م​ ​ل​ل​ج​م​ي​ع​.
		 */
		description: string
		/**
		 * ا​ب​ح​ث​ ​ع​ن​ ​أ​ش​ي​ا​ئ​ك
		 */
		findYourThings: string
	}
	profile: {
		/**
		 * ي​م​ك​ن​ك​ ​ت​غ​ي​ي​ر​ ​ا​س​م​ك​ ​ا​ل​ك​ا​م​ل
		 */
		fullnameChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ا​ل​ا​س​م​ ​ب​ن​ج​ا​ح
		 */
		fullnameChangeSuccess: string
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​د​ي​د​ ​ع​ن​و​ا​ن​ك​ ​ق​ب​ل​ ​إ​ن​ش​ا​ء​ ​م​ن​ش​و​ر​.​ ​ت​أ​ك​د​ ​م​ن​ ​ت​ح​د​ي​د​ ​ا​ل​ع​ن​و​ا​ن​ ​ا​ل​ك​ا​م​ل​ ​م​ع​ ​ا​ل​ر​م​ز​ ​ا​ل​ب​ر​ي​د​ي
		 */
		addressChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ا​ل​ع​ن​و​ا​ن​ ​ب​ن​ج​ا​ح
		 */
		addressChangeSuccess: string
		/**
		 * ي​م​ك​ن​ك​ ​ت​غ​ي​ي​ر​ ​ا​ل​ص​و​ر​ة​ ​ا​ل​ر​م​ز​ي​ة​ ​ا​ل​خ​ا​ص​ة​ ​ب​ك
		 */
		avatarChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ا​ل​ص​و​ر​ة​ ​ا​ل​ر​م​ز​ي​ة​ ​ب​ن​ج​ا​ح
		 */
		avatarChangeSuccess: string
		/**
		 * ي​م​ك​ن​ك​ ​ت​س​ج​ي​ل​ ​ا​ل​خ​ر​و​ج​.​ ​س​ي​ؤ​د​ي​ ​ه​ذ​ا​ ​إ​ل​ى​ ​إ​ن​ه​ا​ء​ ​ج​ل​س​ة​ ​ا​ل​ت​ص​ف​ح​ ​ا​ل​خ​ا​ص​ة​ ​ب​ك
		 */
		logout: string
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​د​ي​د​ ​ر​ق​م​ ​ه​ا​ت​ف​ك​ ​ق​ب​ل​ ​إ​ن​ش​ا​ء​ ​ا​ل​م​ن​ش​و​ر
		 */
		phoneNumberChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ر​ق​م​ ​ا​ل​ه​ا​ت​ف​ ​ب​ن​ج​ا​ح
		 */
		phoneNumberChangeSuccess: string
	}
	posts: {
		/**
		 * م​ن​ش​و​ر​ ​ج​د​ي​د
		 */
		newPost: string
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * تأكيد
		 */
		confirm: () => LocalizedString
		/**
		 * إلغاء
		 */
		cancel: () => LocalizedString
		/**
		 * نجاح
		 */
		success: () => LocalizedString
		/**
		 * خطأ
		 */
		error: () => LocalizedString
		/**
		 * معلومات
		 */
		info: () => LocalizedString
		/**
		 * اختيار
		 */
		select: () => LocalizedString
		/**
		 * اللغة
		 */
		language: () => LocalizedString
		/**
		 * اسحب الملفات وأفلِتها هنا، أو انقر لتحديد الملفات
		 */
		upload: () => LocalizedString
		/**
		 * حدد تاريخا
		 */
		selectDate: () => LocalizedString
		/**
		 * ساعات
		 */
		hours: () => LocalizedString
		/**
		 * دقائق
		 */
		minutes: () => LocalizedString
	}
	errors: {
		/**
		 * غير مسموح
		 */
		forbidden: () => LocalizedString
		/**
		 * غير موجود
		 */
		notFound: () => LocalizedString
		/**
		 * خطأ في الخادم
		 */
		internalServerError: () => LocalizedString
		/**
		 * طلب خاطئ
		 */
		badRequest: () => LocalizedString
		/**
		 * الخدمة غير متوفرة
		 */
		serviceUnavailable: () => LocalizedString
		/**
		 * حدث خطأ أثناء تحميل الملف
		 */
		unableToUploadFile: () => LocalizedString
	}
	schema: {
		/**
		 * الاسم الكامل
		 */
		fullname: () => LocalizedString
		/**
		 * البريد الالكتروني
		 */
		email: () => LocalizedString
		/**
		 * كلمة المرور
		 */
		password: () => LocalizedString
		/**
		 * العنوان الفعلي
		 */
		address: () => LocalizedString
		/**
		 * الصورة الرمزية
		 */
		avatar: () => LocalizedString
		/**
		 * رقم هاتف
		 */
		phoneNumber: () => LocalizedString
	}
	validation: {
		/**
		 * الاسم الكامل يجب أن يكون على الأقل {0} أحرف
		 */
		fullname: (arg0: unknown) => LocalizedString
		/**
		 * عنوان البريد الإلكتروني غير صالح
		 */
		email: () => LocalizedString
		/**
		 * يجب أن يكون عنوانك {0} حرفًا على الأقل
		 */
		address: (arg0: unknown) => LocalizedString
		/**
		 * يجب أن يكون رقم الهاتف مكونًا من 10 أرقام
		 */
		phoneNumber: () => LocalizedString
		/**
		 * حجم الصورة لا يمكن أن يتجاوز {0} ميجا بايت
		 */
		imageSize: (arg0: unknown) => LocalizedString
		/**
		 * يجب عليك تحميل ملف الصورة
		 */
		invalidImageUpload: () => LocalizedString
		/**
		 * يمكنك تحميل ما يصل إلى {0} ملف
		 */
		maxFilesNumber: (arg0: unknown) => LocalizedString
		/**
		 * يجب أن تكون كلمة المرور مكونة من {0} أحرف على الأقل
		 */
		passwordLength: (arg0: unknown) => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف خاص واحد على الأقل
		 */
		passwordSpecialChar: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على رقم واحد على الأقل
		 */
		passwordNumber: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل
		 */
		passwordUppercase: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل
		 */
		passwordLowercase: () => LocalizedString
	}
	auth: {
		/**
		 * تسجيل الدخول
		 */
		login: () => LocalizedString
		/**
		 * إنشاء حساب
		 */
		signup: () => LocalizedString
		/**
		 * لديك حساب بالفعل؟
		 */
		alreadyHaveAccount: () => LocalizedString
		/**
		 * ليس لديك حساب؟
		 */
		dontHaveAccount: () => LocalizedString
		/**
		 * نسيت كلمة المرور؟
		 */
		forgetPassword: () => LocalizedString
		/**
		 * إرسال الرمز
		 */
		sendTheCode: () => LocalizedString
		/**
		 * إعادة إرسال البريد الإلكتروني
		 */
		resendEmail: () => LocalizedString
		/**
		 * تم إعادة إرسال البريد الإلكتروني بنجاح
		 */
		resendSuccess: () => LocalizedString
		/**
		 * تم إرسال الرمز بنجاح
		 */
		sendSuccess: () => LocalizedString
		/**
		 * تم إعادة تعيين كلمة المرور بنجاح
		 */
		resetPasswordSuccess: () => LocalizedString
		/**
		 * تحقق من الرمز
		 */
		verifyCode: () => LocalizedString
		/**
		 * اكتب البريد الإلكتروني الذي نسيت كلمة المرور الخاصة به
		 */
		lostPasswordEmail: () => LocalizedString
		/**
		 * لقد أرسلنا لك كلمة مرور لمرة واحدة؛ تحقق من صندوق الوارد في بريدك الإلكتروني. ثم اكتب كلمة المرور الجديدة.
		 */
		resetPassword: () => LocalizedString
		/**
		 * تأكيد كلمة المرور الجديدة
		 */
		confirmNewPassword: () => LocalizedString
		/**
		 * لقد أرسلنا لك كلمة مرور للتحقق من بريدك الإلكتروني. تحقق من صندوق الوارد الخاص بك؛ إذا لم يكن موجودًا، تحقق من مجلد البريد العشوائي
		 */
		verificationEmail: () => LocalizedString
		/**
		 * يبدو أن هذا الحساب موجود بالفعل
		 */
		acounntAlreadyExist: () => LocalizedString
		/**
		 * يبدو أن هذا الحساب غير موجود
		 */
		accountDoesNotExist: () => LocalizedString
		/**
		 * كلمة المرور غير صحيحة
		 */
		passwordIncorrect: () => LocalizedString
		/**
		 * الرمز غير صحيح
		 */
		incorrectCode: () => LocalizedString
		/**
		 * الرمز منتهي الصلاحية، حاول إعادة الإرسال
		 */
		expiredCode: () => LocalizedString
		/**
		 * تسجيل الخروج
		 */
		logout: () => LocalizedString
	}
	navbar: {
		/**
		 * اختر اللغة
		 */
		selectLanguage: () => LocalizedString
		/**
		 * المنشورات
		 */
		posts: () => LocalizedString
		/**
		 * العلاقات
		 */
		connections: () => LocalizedString
	}
	home: {
		/**
		 * اجد اشيائك المفقودة بدون عناء
		 */
		title: () => LocalizedString
		/**
		 * يعيد لك نظام المطابقة الذكي الخاص بنا العثور على العناصر المفقودة تلقائيًا. نظام آمن وفعال ومصمم للجميع.
		 */
		description: () => LocalizedString
		/**
		 * ابحث عن أشيائك
		 */
		findYourThings: () => LocalizedString
	}
	profile: {
		/**
		 * يمكنك تغيير اسمك الكامل
		 */
		fullnameChange: () => LocalizedString
		/**
		 * تم تغيير الاسم بنجاح
		 */
		fullnameChangeSuccess: () => LocalizedString
		/**
		 * يجب عليك تحديد عنوانك قبل إنشاء منشور. تأكد من تحديد العنوان الكامل مع الرمز البريدي
		 */
		addressChange: () => LocalizedString
		/**
		 * تم تغيير العنوان بنجاح
		 */
		addressChangeSuccess: () => LocalizedString
		/**
		 * يمكنك تغيير الصورة الرمزية الخاصة بك
		 */
		avatarChange: () => LocalizedString
		/**
		 * تم تغيير الصورة الرمزية بنجاح
		 */
		avatarChangeSuccess: () => LocalizedString
		/**
		 * يمكنك تسجيل الخروج. سيؤدي هذا إلى إنهاء جلسة التصفح الخاصة بك
		 */
		logout: () => LocalizedString
		/**
		 * يجب عليك تحديد رقم هاتفك قبل إنشاء المنشور
		 */
		phoneNumberChange: () => LocalizedString
		/**
		 * تم تغيير رقم الهاتف بنجاح
		 */
		phoneNumberChangeSuccess: () => LocalizedString
	}
	posts: {
		/**
		 * منشور جديد
		 */
		newPost: () => LocalizedString
	}
}

export type Formatters = {}
