// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ar'

export type Locales =
	| 'ar'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	selectOptions: {
		/**
		 * أ​خ​ر​ى
		 */
		other: string
		/**
		 * أ​ح​م​ر
		 */
		red: string
		/**
		 * أ​ز​ر​ق
		 */
		blue: string
		/**
		 * أ​خ​ض​ر
		 */
		green: string
		/**
		 * ج​د​ي​د​ ​م​ع​ ​ا​ل​ب​ط​ا​ق​ة
		 */
		newWithTicket: string
		/**
		 * ج​د​ي​د​ ​ب​د​و​ن​ ​ب​ط​ا​ق​ة
		 */
		newWithoutTicket: string
		/**
		 * ح​ا​ل​ة​ ​ج​ي​د​ة
		 */
		good: string
		/**
		 * م​ت​ض​ر​ر
		 */
		damaged: string
		/**
		 * ك​ر​ة​ ​س​ل​ة
		 */
		basketball: string
		/**
		 * ك​ر​ة​ ​ق​د​م​ ​أ​م​ر​ي​ك​ي​ة
		 */
		football: string
		/**
		 * ك​ر​ة​ ​ق​د​م
		 */
		soccerBall: string
		/**
		 * ك​ر​ة​ ​ط​ا​ئ​ر​ة
		 */
		volleyball: string
		/**
		 * ك​ر​ة​ ​ت​ن​س
		 */
		tennisBall: string
		/**
		 * د​ر​ا​ج​ة​ ​ه​و​ا​ئ​ي​ة
		 */
		bicycle: string
		/**
		 * س​ك​و​ت​ر
		 */
		scooter: string
		/**
		 * د​ر​ا​ج​ة​ ​ن​ا​ر​ي​ة
		 */
		motorcycle: string
		/**
		 * ج​ا​ي​ن​ت
		 */
		giant: string
		/**
		 * ت​ر​ي​ك
		 */
		trek: string
		/**
		 * ش​و​ي​ن
		 */
		schwinn: string
		/**
		 * ي​ا​م​ا​ه​ا
		 */
		yamaha: string
		/**
		 * ه​و​ن​د​ا
		 */
		honda: string
		/**
		 * ر​و​س​ي​ن​ي​و​ل
		 */
		rossignol: string
		/**
		 * س​ا​ل​و​م​و​ن
		 */
		salomon: string
		/**
		 * أ​ت​و​م​ي​ك
		 */
		atomic: string
		/**
		 * ب​ل​ا​ك​ ​د​ا​ي​م​و​ن​د
		 */
		blackDiamond: string
		/**
		 * و​ي​ل​س​و​ن
		 */
		wilson: string
		/**
		 * ب​ا​ب​و​ل​ا​ت
		 */
		babolat: string
		/**
		 * ه​ي​د
		 */
		head: string
		/**
		 * ي​و​ن​ك​س
		 */
		yonex: string
		/**
		 * خ​و​ذ​ة​ ​د​ر​ا​ج​ة​ ​ه​و​ا​ئ​ي​ة
		 */
		bicycleHelmet: string
		/**
		 * خ​و​ذ​ة​ ​ت​ز​ل​ج
		 */
		skiHelmet: string
		/**
		 * خ​و​ذ​ة​ ​د​ر​ا​ج​ة​ ​ن​ا​ر​ي​ة
		 */
		motorcycleHelmet: string
		/**
		 * س​و​ن​ي
		 */
		sony: string
		/**
		 * ك​ا​ن​و​ن
		 */
		canon: string
		/**
		 * ن​ي​ك​و​ن
		 */
		nikon: string
		/**
		 * غ​و​ ​ب​ر​و
		 */
		gopro: string
		/**
		 * س​م​ا​ع​ا​ت​ ​ر​أ​س
		 */
		headphones: string
		/**
		 * س​م​ا​ع​ا​ت​ ​ل​ا​س​ل​ك​ي​ة
		 */
		earpods: string
		/**
		 * س​م​ا​ع​ا​ت​ ​أ​ذ​ن
		 */
		earphones: string
		/**
		 * م​ش​غ​ل​ ​M​P​3
		 */
		mp3Player: string
		/**
		 * ق​ا​ر​ئ​ ​إ​ل​ك​ت​ر​و​ن​ي
		 */
		eReader: string
		/**
		 * ك​ا​م​ي​ر​ا​ ​ر​ق​م​ي​ة
		 */
		digitalCamera: string
		/**
		 * U​S​B​-​C
		 */
		usbC: string
		/**
		 * M​i​c​r​o​-​U​S​B
		 */
		microUSB: string
		/**
		 * L​i​g​h​t​n​i​n​g
		 */
		lightning: string
		/**
		 * ل​ا​س​ل​ك​ي
		 */
		wireless: string
		/**
		 * أ​ب​ل
		 */
		apple: string
		/**
		 * د​ل
		 */
		dell: string
		/**
		 * إ​ت​ش​ ​ب​ي
		 */
		hp: string
		/**
		 * ل​ي​ن​و​ف​و
		 */
		lenovo: string
		/**
		 * أ​س​و​س
		 */
		asus: string
		/**
		 * ك​ي​ن​د​ل
		 */
		kindle: string
		/**
		 * ت​ا​ب​ل​ت
		 */
		tablet: string
		/**
		 * س​ا​م​س​و​ن​ج
		 */
		samsung: string
		/**
		 * أ​م​ا​ز​و​ن
		 */
		amazon: string
		/**
		 * ف​ي​ت​ب​ي​ت
		 */
		fitbit: string
		/**
		 * ج​ا​ر​م​ن
		 */
		garmin: string
		/**
		 * ن​ي​ن​ت​ن​د​و
		 */
		nintendo: string
		/**
		 * غ​و​غ​ل
		 */
		google: string
		/**
		 * و​ا​ن​ ​ب​ل​س
		 */
		onePlus: string
		/**
		 * ا​ل​و​ل​ا​ي​ا​ت​ ​ا​ل​م​ت​ح​د​ة
		 */
		unitedStates: string
		/**
		 * ك​ن​د​ا
		 */
		canada: string
		/**
		 * ا​ل​م​م​ل​ك​ة​ ​ا​ل​م​ت​ح​د​ة
		 */
		unitedKingdom: string
		/**
		 * أ​ل​م​ا​ن​ي​ا
		 */
		germany: string
		/**
		 * ف​ر​ن​س​ا
		 */
		france: string
		/**
		 * ا​ل​ي​ا​ب​ا​ن
		 */
		japan: string
		/**
		 * ا​ل​ص​ي​ن
		 */
		china: string
		/**
		 * أ​س​ت​ر​ا​ل​ي​ا
		 */
		australia: string
		/**
		 * ا​ل​ب​ر​ا​ز​ي​ل
		 */
		brazil: string
		/**
		 * ا​ل​ه​ن​د
		 */
		india: string
	}
	metaData: {
		/**
		 * ل​و​ن
		 */
		color: string
		/**
		 * ح​ا​ل​ة
		 */
		condition: string
		/**
		 * ن​و​ع​ ​ا​ل​ك​ر​ة
		 */
		ballType: string
		/**
		 * ن​و​ع​ ​ا​ل​م​ر​ك​ب​ة​ ​ث​ن​ا​ئ​ي​ة​ ​ا​ل​ع​ج​ل​ا​ت
		 */
		twoWheelerType: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​م​ر​ك​ب​ة​ ​ث​ن​ا​ئ​ي​ة​ ​ا​ل​ع​ج​ل​ا​ت
		 */
		twoWheelerBrand: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​ت​ز​ل​ج​ ​أ​و​ ​ا​ل​ع​ص​ي
		 */
		skiOrPolesBrand: string
		/**
		 * م​ا​ر​ك​ة​ ​م​ض​ر​ب​ ​ا​ل​ت​ن​س
		 */
		tennisRacketBrand: string
		/**
		 * ن​و​ع​ ​ا​ل​خ​و​ذ​ة
		 */
		helmetType: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​خ​و​ذ​ة
		 */
		helmetBrand: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​ك​ا​م​ي​ر​ا
		 */
		cameraVideoRecorderBrand: string
		/**
		 * ط​ر​ا​ز​ ​ا​ل​ك​ا​م​ي​ر​ا
		 */
		cameraVideoRecorderModel: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​ح​ا​س​و​ب
		 */
		computerBrand: string
		/**
		 * ط​ر​ا​ز​ ​ا​ل​ح​ا​س​و​ب
		 */
		computerModel: string
		/**
		 * خ​ل​ف​ي​ة​ ​ا​ل​ح​ا​س​و​ب
		 */
		computerWallpaper: string
		/**
		 * ن​و​ع​ ​ا​ل​ش​ا​ح​ن
		 */
		chargerType: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​ش​ا​ح​ن
		 */
		chargerBrand: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​ج​ه​ا​ز​ ​ا​ل​ل​و​ح​ي
		 */
		tabletBrand: string
		/**
		 * ط​ر​ا​ز​ ​ا​ل​ج​ه​ا​ز​ ​ا​ل​ل​و​ح​ي
		 */
		tabletModel: string
		/**
		 * خ​ل​ف​ي​ة​ ​ا​ل​ج​ه​ا​ز​ ​ا​ل​ل​و​ح​ي
		 */
		tabletWallpaper: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​س​ا​ع​ة​ ​ا​ل​ذ​ك​ي​ة
		 */
		smartwatchBrand: string
		/**
		 * ط​ر​ا​ز​ ​ا​ل​س​ا​ع​ة​ ​ا​ل​ذ​ك​ي​ة
		 */
		smartwatchModel: string
		/**
		 * م​ا​ر​ك​ة​ ​ا​ل​ه​ا​ت​ف
		 */
		phoneBrand: string
		/**
		 * ط​ر​ا​ز​ ​ا​ل​ه​ا​ت​ف
		 */
		phoneModel: string
		/**
		 * خ​ل​ف​ي​ة​ ​ا​ل​ه​ا​ت​ف
		 */
		phoneWallpaper: string
		/**
		 * ا​ل​ب​ل​د​ ​ا​ل​م​ص​د​ر
		 */
		issuingCountry: string
		/**
		 * ا​ل​ا​س​م
		 */
		name: string
		/**
		 * ت​ا​ر​ي​خ​ ​ا​ل​م​ي​ل​ا​د
		 */
		birthDate: string
		/**
		 * ا​س​م​ ​ا​ل​ش​ر​ك​ة
		 */
		companyName: string
		/**
		 * ا​س​م​ ​ص​ا​ح​ب​ ​ا​ل​ع​م​ل
		 */
		employerName: string
	}
	categories: {
		/**
		 * م​ع​د​ا​ت​ ​ر​ي​ا​ض​ي​ة
		 */
		sportEquipments: string
		/**
		 * ك​ر​ة
		 */
		ball: string
		/**
		 * د​ر​ا​ج​ة​ ​ذ​ا​ت​ ​ع​ج​ل​ت​ي​ن
		 */
		twoWheeler: string
		/**
		 * ز​ل​ا​ج​ا​ت​ ​أ​و​ ​ع​ص​ي​ ​ت​ز​ل​ج
		 */
		skiOrPoles: string
		/**
		 * م​ض​ر​ب​ ​ت​ن​س
		 */
		tennisRacket: string
		/**
		 * خ​و​ذ​ة
		 */
		helmet: string
		/**
		 * إ​ل​ك​ت​ر​و​ن​ي​ا​ت
		 */
		electronics: string
		/**
		 * ك​ا​م​ي​ر​ا​ ​م​س​ج​ل​ ​ف​ي​د​ي​و
		 */
		cameraVideoRecorder: string
		/**
		 * ح​ا​س​و​ب
		 */
		computer: string
		/**
		 * ش​ا​ح​ن
		 */
		charger: string
		/**
		 * ج​ه​ا​ز​ ​ل​و​ح​ي
		 */
		tablet: string
		/**
		 * س​ا​ع​ة​ ​ذ​ك​ي​ة
		 */
		smartwatch: string
		/**
		 * ه​ا​ت​ف
		 */
		phone: string
		/**
		 * و​ث​ا​ئ​ق
		 */
		documents: string
		/**
		 * ب​ط​ا​ق​ة​ ​ه​و​ي​ة
		 */
		idCard: string
		/**
		 * ج​و​ا​ز​ ​س​ف​ر
		 */
		passport: string
		/**
		 * ر​خ​ص​ة​ ​ق​ي​ا​د​ة
		 */
		driverLicense: string
		/**
		 * ش​ا​ر​ة​ ​ا​ل​ش​ر​ك​ة
		 */
		companyBadget: string
	}
	transports: {
		/**
		 * س​ي​ا​ر​ة
		 */
		car: string
		/**
		 * ت​ر​ا​م​و​ا​ي
		 */
		tramway: string
		/**
		 * ح​ا​ف​ل​ة
		 */
		bus: string
		/**
		 * ق​ط​ا​ر
		 */
		train: string
	}
	general: {
		/**
		 * ت​أ​ك​ي​د
		 */
		confirm: string
		/**
		 * إ​ل​غ​ا​ء
		 */
		cancel: string
		/**
		 * ن​ج​ا​ح
		 */
		success: string
		/**
		 * خ​ط​أ
		 */
		error: string
		/**
		 * م​ع​ل​و​م​ا​ت
		 */
		info: string
		/**
		 * ا​خ​ت​ي​ا​ر
		 */
		select: string
		/**
		 * ا​ل​ل​غ​ة
		 */
		language: string
		/**
		 * ا​س​ح​ب​ ​ا​ل​م​ل​ف​ا​ت​ ​و​أ​ف​ل​ِ​ت​ه​ا​ ​ه​ن​ا​،​ ​أ​و​ ​ا​ن​ق​ر​ ​ل​ت​ح​د​ي​د​ ​ا​ل​م​ل​ف​ا​ت
		 */
		upload: string
		/**
		 * ح​د​د​ ​ت​ا​ر​ي​خ​ا
		 */
		selectDate: string
		/**
		 * ا​ب​ح​ث​ ​ع​ن​ ​ع​ن​و​ا​ن
		 */
		searchAddress: string
		/**
		 * ت​ا​ر​ي​خ
		 */
		date: string
		/**
		 * س​ا​ع​ا​ت
		 */
		hours: string
		/**
		 * د​ق​ا​ئ​ق
		 */
		minutes: string
		/**
		 * ا​ل​س​ن​ة​ 
		 */
		year: string
		/**
		 * ا​ل​ش​ه​ر
		 */
		month: string
		/**
		 * و​س​ي​ل​ة​ ​ن​ق​ل
		 */
		transportMethod: string
	}
	errors: {
		/**
		 * غ​ي​ر​ ​م​س​م​و​ح
		 */
		forbidden: string
		/**
		 * غ​ي​ر​ ​م​و​ج​و​د
		 */
		notFound: string
		/**
		 * خ​ط​أ​ ​ف​ي​ ​ا​ل​خ​ا​د​م
		 */
		internalServerError: string
		/**
		 * ط​ل​ب​ ​خ​ا​ط​ئ
		 */
		badRequest: string
		/**
		 * ا​ل​خ​د​م​ة​ ​غ​ي​ر​ ​م​ت​و​ف​ر​ة
		 */
		serviceUnavailable: string
		/**
		 * ح​د​ث​ ​خ​ط​أ​ ​أ​ث​ن​ا​ء​ ​ت​ح​م​ي​ل​ ​ا​ل​م​ل​ف
		 */
		unableToUploadFile: string
	}
	schema: {
		/**
		 * ا​ل​ا​س​م​ ​ا​ل​ك​ا​م​ل
		 */
		fullname: string
		/**
		 * ا​ل​ب​ر​ي​د​ ​ا​ل​ا​ل​ك​ت​ر​و​ن​ي
		 */
		email: string
		/**
		 * ك​ل​م​ة​ ​ا​ل​م​ر​و​ر
		 */
		password: string
		/**
		 * ا​ل​ع​ن​و​ا​ن​ ​ا​ل​ف​ع​ل​ي
		 */
		address: string
		/**
		 * ا​ل​ص​و​ر​ة​ ​ا​ل​ر​م​ز​ي​ة
		 */
		avatar: string
		/**
		 * ر​ق​م​ ​ه​ا​ت​ف
		 */
		phoneNumber: string
	}
	validation: {
		/**
		 * ا​ل​ا​س​م​ ​ا​ل​ك​ا​م​ل​ ​ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل​ ​{​0​}​ ​أ​ح​ر​ف
		 * @param {unknown} 0
		 */
		fullname: RequiredParams<'0'>
		/**
		 * ع​ن​و​ا​ن​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​غ​ي​ر​ ​ص​ا​ل​ح
		 */
		email: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ع​ن​و​ا​ن​ ​{​0​}​ ​ح​ر​ف​ً​ا​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 * @param {unknown} 0
		 */
		address: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ي​ك​و​ن​ ​ر​ق​م​ ​ا​ل​ه​ا​ت​ف​ ​م​ك​و​ن​ً​ا​ ​م​ن​ ​1​0​ ​أ​ر​ق​ا​م
		 */
		phoneNumber: string
		/**
		 * ح​ج​م​ ​ا​ل​ص​و​ر​ة​ ​ل​ا​ ​ي​م​ك​ن​ ​أ​ن​ ​ي​ت​ج​ا​و​ز​ ​{​0​}​ ​م​ي​ج​ا​ ​ب​ا​ي​ت
		 * @param {unknown} 0
		 */
		imageSize: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​م​ي​ل​ ​م​ل​ف​ ​ا​ل​ص​و​ر​ة
		 */
		invalidImageUpload: string
		/**
		 * ي​م​ك​ن​ك​ ​ت​ح​م​ي​ل​ ​م​ا​ ​ي​ص​ل​ ​إ​ل​ى​ ​{​0​}​ ​م​ل​ف
		 * @param {unknown} 0
		 */
		maxFilesNumber: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ك​و​ن​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​م​ك​و​ن​ة​ ​م​ن​ ​{​0​}​ ​أ​ح​ر​ف​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 * @param {unknown} 0
		 */
		passwordLength: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​خ​ا​ص​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordSpecialChar: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ر​ق​م​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordNumber: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​ك​ب​ي​ر​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordUppercase: string
		/**
		 * ي​ج​ب​ ​أ​ن​ ​ت​ح​ت​و​ي​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ع​ل​ى​ ​ح​ر​ف​ ​ص​غ​ي​ر​ ​و​ا​ح​د​ ​ع​ل​ى​ ​ا​ل​أ​ق​ل
		 */
		passwordLowercase: string
		/**
		 * ل​ا​ ​ي​م​ك​ن​ ​أ​ن​ ​ي​ت​ج​ا​و​ز​ ​ط​و​ل​ ​ا​ل​ن​ص​ ​{​0​}​ ​ح​ر​ف​ً​ا
		 * @param {unknown} 0
		 */
		metaDataText: RequiredParams<'0'>
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​د​ي​د​ ​ت​ا​ر​ي​خ
		 */
		itemDate: string
		/**
		 * ت​ح​ت​ا​ج​ ​إ​ل​ى​ ​ت​ح​د​ي​د​ ​ف​ئ​ة
		 */
		itemCategory: string
		/**
		 * ع​ن​و​ا​ن​ ​ش​ي​ء​ ​غ​ي​ر​ ​ص​ا​ل​ح
		 */
		invalidItemAddress: string
	}
	auth: {
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​د​خ​و​ل
		 */
		login: string
		/**
		 * إ​ن​ش​ا​ء​ ​ح​س​ا​ب
		 */
		signup: string
		/**
		 * ل​د​ي​ك​ ​ح​س​ا​ب​ ​ب​ا​ل​ف​ع​ل​؟
		 */
		alreadyHaveAccount: string
		/**
		 * ل​ي​س​ ​ل​د​ي​ك​ ​ح​س​ا​ب​؟
		 */
		dontHaveAccount: string
		/**
		 * ن​س​ي​ت​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​؟
		 */
		forgetPassword: string
		/**
		 * إ​ر​س​ا​ل​ ​ا​ل​ر​م​ز
		 */
		sendTheCode: string
		/**
		 * إ​ع​ا​د​ة​ ​إ​ر​س​ا​ل​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي
		 */
		resendEmail: string
		/**
		 * ت​م​ ​إ​ع​ا​د​ة​ ​إ​ر​س​ا​ل​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​ب​ن​ج​ا​ح
		 */
		resendSuccess: string
		/**
		 * ت​م​ ​إ​ر​س​ا​ل​ ​ا​ل​ر​م​ز​ ​ب​ن​ج​ا​ح
		 */
		sendSuccess: string
		/**
		 * ت​م​ ​إ​ع​ا​د​ة​ ​ت​ع​ي​ي​ن​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ب​ن​ج​ا​ح
		 */
		resetPasswordSuccess: string
		/**
		 * ت​ح​ق​ق​ ​م​ن​ ​ا​ل​ر​م​ز
		 */
		verifyCode: string
		/**
		 * ا​ك​ت​ب​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​ ​ا​ل​ذ​ي​ ​ن​س​ي​ت​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​خ​ا​ص​ة​ ​ب​ه
		 */
		lostPasswordEmail: string
		/**
		 * ل​ق​د​ ​أ​ر​س​ل​ن​ا​ ​ل​ك​ ​ك​ل​م​ة​ ​م​ر​و​ر​ ​ل​م​ر​ة​ ​و​ا​ح​د​ة​؛​ ​ت​ح​ق​ق​ ​م​ن​ ​ص​ن​د​و​ق​ ​ا​ل​و​ا​ر​د​ ​ف​ي​ ​ب​ر​ي​د​ك​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​.​ ​ث​م​ ​ا​ك​ت​ب​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​ج​د​ي​د​ة​.
		 */
		resetPassword: string
		/**
		 * ت​أ​ك​ي​د​ ​ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​ا​ل​ج​د​ي​د​ة
		 */
		confirmNewPassword: string
		/**
		 * ل​ق​د​ ​أ​ر​س​ل​ن​ا​ ​ل​ك​ ​ك​ل​م​ة​ ​م​ر​و​ر​ ​ل​ل​ت​ح​ق​ق​ ​م​ن​ ​ب​ر​ي​د​ك​ ​ا​ل​إ​ل​ك​ت​ر​و​ن​ي​.​ ​ت​ح​ق​ق​ ​م​ن​ ​ص​ن​د​و​ق​ ​ا​ل​و​ا​ر​د​ ​ا​ل​خ​ا​ص​ ​ب​ك​؛​ ​إ​ذ​ا​ ​ل​م​ ​ي​ك​ن​ ​م​و​ج​و​د​ً​ا​،​ ​ت​ح​ق​ق​ ​م​ن​ ​م​ج​ل​د​ ​ا​ل​ب​ر​ي​د​ ​ا​ل​ع​ش​و​ا​ئ​ي
		 */
		verificationEmail: string
		/**
		 * ي​ب​د​و​ ​أ​ن​ ​ه​ذ​ا​ ​ا​ل​ح​س​ا​ب​ ​م​و​ج​و​د​ ​ب​ا​ل​ف​ع​ل
		 */
		acounntAlreadyExist: string
		/**
		 * ي​ب​د​و​ ​أ​ن​ ​ه​ذ​ا​ ​ا​ل​ح​س​ا​ب​ ​غ​ي​ر​ ​م​و​ج​و​د
		 */
		accountDoesNotExist: string
		/**
		 * ك​ل​م​ة​ ​ا​ل​م​ر​و​ر​ ​غ​ي​ر​ ​ص​ح​ي​ح​ة
		 */
		passwordIncorrect: string
		/**
		 * ا​ل​ر​م​ز​ ​غ​ي​ر​ ​ص​ح​ي​ح
		 */
		incorrectCode: string
		/**
		 * ا​ل​ر​م​ز​ ​م​ن​ت​ه​ي​ ​ا​ل​ص​ل​ا​ح​ي​ة​،​ ​ح​ا​و​ل​ ​إ​ع​ا​د​ة​ ​ا​ل​إ​ر​س​ا​ل
		 */
		expiredCode: string
		/**
		 * ت​س​ج​ي​ل​ ​ا​ل​خ​ر​و​ج
		 */
		logout: string
	}
	navbar: {
		/**
		 * ا​خ​ت​ر​ ​ا​ل​ل​غ​ة
		 */
		selectLanguage: string
		/**
		 * ا​ل​م​ن​ش​و​ر​ا​ت
		 */
		posts: string
		/**
		 * ا​ل​ع​ل​ا​ق​ا​ت
		 */
		connections: string
	}
	home: {
		/**
		 * ا​ج​د​ ​ا​ش​ي​ا​ئ​ك​ ​ا​ل​م​ف​ق​و​د​ة​ ​ب​د​و​ن​ ​ع​ن​ا​ء
		 */
		title: string
		/**
		 * ي​ع​ي​د​ ​ل​ك​ ​ن​ظ​ا​م​ ​ا​ل​م​ط​ا​ب​ق​ة​ ​ا​ل​ذ​ك​ي​ ​ا​ل​خ​ا​ص​ ​ب​ن​ا​ ​ا​ل​ع​ث​و​ر​ ​ع​ل​ى​ ​ا​ل​ع​ن​ا​ص​ر​ ​ا​ل​م​ف​ق​و​د​ة​ ​ت​ل​ق​ا​ئ​ي​ً​ا​.​ ​ن​ظ​ا​م​ ​آ​م​ن​ ​و​ف​ع​ا​ل​ ​و​م​ص​م​م​ ​ل​ل​ج​م​ي​ع​.
		 */
		description: string
		/**
		 * ا​ب​ح​ث​ ​ع​ن​ ​أ​ش​ي​ا​ئ​ك
		 */
		findYourThings: string
	}
	profile: {
		/**
		 * ي​م​ك​ن​ك​ ​ت​غ​ي​ي​ر​ ​ا​س​م​ك​ ​ا​ل​ك​ا​م​ل
		 */
		fullnameChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ا​ل​ا​س​م​ ​ب​ن​ج​ا​ح
		 */
		fullnameChangeSuccess: string
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​د​ي​د​ ​ع​ن​و​ا​ن​ك​ ​ق​ب​ل​ ​إ​ن​ش​ا​ء​ ​م​ن​ش​و​ر​.​ ​ت​أ​ك​د​ ​م​ن​ ​ت​ح​د​ي​د​ ​ا​ل​ع​ن​و​ا​ن​ ​ا​ل​ك​ا​م​ل​ ​م​ع​ ​ا​ل​ر​م​ز​ ​ا​ل​ب​ر​ي​د​ي
		 */
		addressChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ا​ل​ع​ن​و​ا​ن​ ​ب​ن​ج​ا​ح
		 */
		addressChangeSuccess: string
		/**
		 * ي​م​ك​ن​ك​ ​ت​غ​ي​ي​ر​ ​ا​ل​ص​و​ر​ة​ ​ا​ل​ر​م​ز​ي​ة​ ​ا​ل​خ​ا​ص​ة​ ​ب​ك
		 */
		avatarChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ا​ل​ص​و​ر​ة​ ​ا​ل​ر​م​ز​ي​ة​ ​ب​ن​ج​ا​ح
		 */
		avatarChangeSuccess: string
		/**
		 * ي​م​ك​ن​ك​ ​ت​س​ج​ي​ل​ ​ا​ل​خ​ر​و​ج​.​ ​س​ي​ؤ​د​ي​ ​ه​ذ​ا​ ​إ​ل​ى​ ​إ​ن​ه​ا​ء​ ​ج​ل​س​ة​ ​ا​ل​ت​ص​ف​ح​ ​ا​ل​خ​ا​ص​ة​ ​ب​ك
		 */
		logout: string
		/**
		 * ي​ج​ب​ ​ع​ل​ي​ك​ ​ت​ح​د​ي​د​ ​ر​ق​م​ ​ه​ا​ت​ف​ك​ ​ق​ب​ل​ ​إ​ن​ش​ا​ء​ ​ا​ل​م​ن​ش​و​ر
		 */
		phoneNumberChange: string
		/**
		 * ت​م​ ​ت​غ​ي​ي​ر​ ​ر​ق​م​ ​ا​ل​ه​ا​ت​ف​ ​ب​ن​ج​ا​ح
		 */
		phoneNumberChangeSuccess: string
	}
	posts: {
		/**
		 * م​ن​ش​و​ر​ ​ج​د​ي​د
		 */
		newPost: string
		/**
		 * ا​ل​ع​و​د​ة​ ​إ​ل​ى​ ​ا​ل​ف​ئ​ا​ت
		 */
		returnCategories: string
		/**
		 * م​ف​ق​و​د
		 */
		lost: string
		/**
		 * م​و​ج​و​د
		 */
		found: string
		/**
		 * ا​خ​ت​ر​ ​ن​و​ع​ ​ا​ل​ش​ي​ء
		 */
		selectItemType: string
		/**
		 * ا​ل​ب​ي​ا​ن​ا​ت​ ​ا​ل​و​ص​ف​ي​ة​ ​ل​ل​ش​ي​ء​ ​ل​ه​ا​ ​ق​ي​م​ ​ا​ف​ت​ر​ا​ض​ي​ة​.​ ​إ​ذ​ا​ ​ك​ن​ت​ ​ل​ا​ ​ت​ع​ر​ف​ ​ق​ي​م​ه​ا​ ​ف​ل​ا​ ​ت​ق​م​ ​ب​ت​ع​ي​ي​ن​ه​ا
		 */
		createDescription: string
		/**
		 * أ​ي​ن​ ​ف​ق​د​ت​ ​ا​ل​ش​ي​ء​؟
		 */
		whereYouLost: string
		/**
		 * م​ت​ى​ ​ف​ق​د​ت​ ​ا​ل​ش​ي​ء​؟
		 */
		whenYouLost: string
		/**
		 * م​ت​ى​ ​و​ج​د​ت​ ​ا​ل​ش​ي​ء​؟
		 */
		whenYouFound: string
		/**
		 * أ​ي​ن​ ​و​ج​د​ت​ ​ا​ل​ش​ي​ء​؟
		 */
		whereYouFound: string
		/**
		 * ي​م​ك​ن​ك​ ​ك​ت​ا​ب​ة​ ​و​ص​ف​ ​ك​ا​م​ل​ ​ل​ل​ع​ن​ص​ر​ ​ا​ل​م​ف​ق​و​د
		 */
		lostItemDescription: string
		/**
		 * ص​و​ر​ ​ت​ظ​ه​ر​ ​ا​ل​ع​ن​ص​ر​ ​ا​ل​خ​ا​ص​ ​ب​ك
		 */
		lostItemImages: string
		/**
		 * ا​ل​ن​ق​ل
		 */
		transport: string
		/**
		 * ا​ل​ع​ن​و​ا​ن
		 */
		address: string
		/**
		 * ن​ق​ط​ة​ ​ا​ن​ط​ل​ا​ق​ ​ا​ل​ن​ق​ل
		 */
		transportStart: string
		/**
		 * ن​ق​ط​ة​ ​ا​ن​ت​ه​ا​ء​ ​ا​ل​ن​ق​ل
		 */
		transportEnd: string
		/**
		 * إ​ض​ا​ف​ة​ ​ع​ن​و​ا​ن​ ​إ​ض​ا​ف​ي
		 */
		additionalAddress: string
		/**
		 * ن​و​ع
		 */
		postType: string
		/**
		 * ا​ل​ح​ا​ل​ة
		 */
		postState: string
		/**
		 * ا​ل​ف​ئ​ة
		 */
		itemCategory: string
		/**
		 * ا​ل​م​ز​ي​د​ ​م​ن​ ​ا​ل​م​ع​ل​و​م​ا​ت
		 */
		seeInfo: string
	}
	postStates: {
		/**
		 * ع​ا​ط​ل
		 */
		idle: string
		/**
		 * م​ط​ا​ب​ق​ة
		 */
		matched: string
	}
}

export type TranslationFunctions = {
	selectOptions: {
		/**
		 * أخرى
		 */
		other: () => LocalizedString
		/**
		 * أحمر
		 */
		red: () => LocalizedString
		/**
		 * أزرق
		 */
		blue: () => LocalizedString
		/**
		 * أخضر
		 */
		green: () => LocalizedString
		/**
		 * جديد مع البطاقة
		 */
		newWithTicket: () => LocalizedString
		/**
		 * جديد بدون بطاقة
		 */
		newWithoutTicket: () => LocalizedString
		/**
		 * حالة جيدة
		 */
		good: () => LocalizedString
		/**
		 * متضرر
		 */
		damaged: () => LocalizedString
		/**
		 * كرة سلة
		 */
		basketball: () => LocalizedString
		/**
		 * كرة قدم أمريكية
		 */
		football: () => LocalizedString
		/**
		 * كرة قدم
		 */
		soccerBall: () => LocalizedString
		/**
		 * كرة طائرة
		 */
		volleyball: () => LocalizedString
		/**
		 * كرة تنس
		 */
		tennisBall: () => LocalizedString
		/**
		 * دراجة هوائية
		 */
		bicycle: () => LocalizedString
		/**
		 * سكوتر
		 */
		scooter: () => LocalizedString
		/**
		 * دراجة نارية
		 */
		motorcycle: () => LocalizedString
		/**
		 * جاينت
		 */
		giant: () => LocalizedString
		/**
		 * تريك
		 */
		trek: () => LocalizedString
		/**
		 * شوين
		 */
		schwinn: () => LocalizedString
		/**
		 * ياماها
		 */
		yamaha: () => LocalizedString
		/**
		 * هوندا
		 */
		honda: () => LocalizedString
		/**
		 * روسينيول
		 */
		rossignol: () => LocalizedString
		/**
		 * سالومون
		 */
		salomon: () => LocalizedString
		/**
		 * أتوميك
		 */
		atomic: () => LocalizedString
		/**
		 * بلاك دايموند
		 */
		blackDiamond: () => LocalizedString
		/**
		 * ويلسون
		 */
		wilson: () => LocalizedString
		/**
		 * بابولات
		 */
		babolat: () => LocalizedString
		/**
		 * هيد
		 */
		head: () => LocalizedString
		/**
		 * يونكس
		 */
		yonex: () => LocalizedString
		/**
		 * خوذة دراجة هوائية
		 */
		bicycleHelmet: () => LocalizedString
		/**
		 * خوذة تزلج
		 */
		skiHelmet: () => LocalizedString
		/**
		 * خوذة دراجة نارية
		 */
		motorcycleHelmet: () => LocalizedString
		/**
		 * سوني
		 */
		sony: () => LocalizedString
		/**
		 * كانون
		 */
		canon: () => LocalizedString
		/**
		 * نيكون
		 */
		nikon: () => LocalizedString
		/**
		 * غو برو
		 */
		gopro: () => LocalizedString
		/**
		 * سماعات رأس
		 */
		headphones: () => LocalizedString
		/**
		 * سماعات لاسلكية
		 */
		earpods: () => LocalizedString
		/**
		 * سماعات أذن
		 */
		earphones: () => LocalizedString
		/**
		 * مشغل MP3
		 */
		mp3Player: () => LocalizedString
		/**
		 * قارئ إلكتروني
		 */
		eReader: () => LocalizedString
		/**
		 * كاميرا رقمية
		 */
		digitalCamera: () => LocalizedString
		/**
		 * USB-C
		 */
		usbC: () => LocalizedString
		/**
		 * Micro-USB
		 */
		microUSB: () => LocalizedString
		/**
		 * Lightning
		 */
		lightning: () => LocalizedString
		/**
		 * لاسلكي
		 */
		wireless: () => LocalizedString
		/**
		 * أبل
		 */
		apple: () => LocalizedString
		/**
		 * دل
		 */
		dell: () => LocalizedString
		/**
		 * إتش بي
		 */
		hp: () => LocalizedString
		/**
		 * لينوفو
		 */
		lenovo: () => LocalizedString
		/**
		 * أسوس
		 */
		asus: () => LocalizedString
		/**
		 * كيندل
		 */
		kindle: () => LocalizedString
		/**
		 * تابلت
		 */
		tablet: () => LocalizedString
		/**
		 * سامسونج
		 */
		samsung: () => LocalizedString
		/**
		 * أمازون
		 */
		amazon: () => LocalizedString
		/**
		 * فيتبيت
		 */
		fitbit: () => LocalizedString
		/**
		 * جارمن
		 */
		garmin: () => LocalizedString
		/**
		 * نينتندو
		 */
		nintendo: () => LocalizedString
		/**
		 * غوغل
		 */
		google: () => LocalizedString
		/**
		 * وان بلس
		 */
		onePlus: () => LocalizedString
		/**
		 * الولايات المتحدة
		 */
		unitedStates: () => LocalizedString
		/**
		 * كندا
		 */
		canada: () => LocalizedString
		/**
		 * المملكة المتحدة
		 */
		unitedKingdom: () => LocalizedString
		/**
		 * ألمانيا
		 */
		germany: () => LocalizedString
		/**
		 * فرنسا
		 */
		france: () => LocalizedString
		/**
		 * اليابان
		 */
		japan: () => LocalizedString
		/**
		 * الصين
		 */
		china: () => LocalizedString
		/**
		 * أستراليا
		 */
		australia: () => LocalizedString
		/**
		 * البرازيل
		 */
		brazil: () => LocalizedString
		/**
		 * الهند
		 */
		india: () => LocalizedString
	}
	metaData: {
		/**
		 * لون
		 */
		color: () => LocalizedString
		/**
		 * حالة
		 */
		condition: () => LocalizedString
		/**
		 * نوع الكرة
		 */
		ballType: () => LocalizedString
		/**
		 * نوع المركبة ثنائية العجلات
		 */
		twoWheelerType: () => LocalizedString
		/**
		 * ماركة المركبة ثنائية العجلات
		 */
		twoWheelerBrand: () => LocalizedString
		/**
		 * ماركة التزلج أو العصي
		 */
		skiOrPolesBrand: () => LocalizedString
		/**
		 * ماركة مضرب التنس
		 */
		tennisRacketBrand: () => LocalizedString
		/**
		 * نوع الخوذة
		 */
		helmetType: () => LocalizedString
		/**
		 * ماركة الخوذة
		 */
		helmetBrand: () => LocalizedString
		/**
		 * ماركة الكاميرا
		 */
		cameraVideoRecorderBrand: () => LocalizedString
		/**
		 * طراز الكاميرا
		 */
		cameraVideoRecorderModel: () => LocalizedString
		/**
		 * ماركة الحاسوب
		 */
		computerBrand: () => LocalizedString
		/**
		 * طراز الحاسوب
		 */
		computerModel: () => LocalizedString
		/**
		 * خلفية الحاسوب
		 */
		computerWallpaper: () => LocalizedString
		/**
		 * نوع الشاحن
		 */
		chargerType: () => LocalizedString
		/**
		 * ماركة الشاحن
		 */
		chargerBrand: () => LocalizedString
		/**
		 * ماركة الجهاز اللوحي
		 */
		tabletBrand: () => LocalizedString
		/**
		 * طراز الجهاز اللوحي
		 */
		tabletModel: () => LocalizedString
		/**
		 * خلفية الجهاز اللوحي
		 */
		tabletWallpaper: () => LocalizedString
		/**
		 * ماركة الساعة الذكية
		 */
		smartwatchBrand: () => LocalizedString
		/**
		 * طراز الساعة الذكية
		 */
		smartwatchModel: () => LocalizedString
		/**
		 * ماركة الهاتف
		 */
		phoneBrand: () => LocalizedString
		/**
		 * طراز الهاتف
		 */
		phoneModel: () => LocalizedString
		/**
		 * خلفية الهاتف
		 */
		phoneWallpaper: () => LocalizedString
		/**
		 * البلد المصدر
		 */
		issuingCountry: () => LocalizedString
		/**
		 * الاسم
		 */
		name: () => LocalizedString
		/**
		 * تاريخ الميلاد
		 */
		birthDate: () => LocalizedString
		/**
		 * اسم الشركة
		 */
		companyName: () => LocalizedString
		/**
		 * اسم صاحب العمل
		 */
		employerName: () => LocalizedString
	}
	categories: {
		/**
		 * معدات رياضية
		 */
		sportEquipments: () => LocalizedString
		/**
		 * كرة
		 */
		ball: () => LocalizedString
		/**
		 * دراجة ذات عجلتين
		 */
		twoWheeler: () => LocalizedString
		/**
		 * زلاجات أو عصي تزلج
		 */
		skiOrPoles: () => LocalizedString
		/**
		 * مضرب تنس
		 */
		tennisRacket: () => LocalizedString
		/**
		 * خوذة
		 */
		helmet: () => LocalizedString
		/**
		 * إلكترونيات
		 */
		electronics: () => LocalizedString
		/**
		 * كاميرا مسجل فيديو
		 */
		cameraVideoRecorder: () => LocalizedString
		/**
		 * حاسوب
		 */
		computer: () => LocalizedString
		/**
		 * شاحن
		 */
		charger: () => LocalizedString
		/**
		 * جهاز لوحي
		 */
		tablet: () => LocalizedString
		/**
		 * ساعة ذكية
		 */
		smartwatch: () => LocalizedString
		/**
		 * هاتف
		 */
		phone: () => LocalizedString
		/**
		 * وثائق
		 */
		documents: () => LocalizedString
		/**
		 * بطاقة هوية
		 */
		idCard: () => LocalizedString
		/**
		 * جواز سفر
		 */
		passport: () => LocalizedString
		/**
		 * رخصة قيادة
		 */
		driverLicense: () => LocalizedString
		/**
		 * شارة الشركة
		 */
		companyBadget: () => LocalizedString
	}
	transports: {
		/**
		 * سيارة
		 */
		car: () => LocalizedString
		/**
		 * ترامواي
		 */
		tramway: () => LocalizedString
		/**
		 * حافلة
		 */
		bus: () => LocalizedString
		/**
		 * قطار
		 */
		train: () => LocalizedString
	}
	general: {
		/**
		 * تأكيد
		 */
		confirm: () => LocalizedString
		/**
		 * إلغاء
		 */
		cancel: () => LocalizedString
		/**
		 * نجاح
		 */
		success: () => LocalizedString
		/**
		 * خطأ
		 */
		error: () => LocalizedString
		/**
		 * معلومات
		 */
		info: () => LocalizedString
		/**
		 * اختيار
		 */
		select: () => LocalizedString
		/**
		 * اللغة
		 */
		language: () => LocalizedString
		/**
		 * اسحب الملفات وأفلِتها هنا، أو انقر لتحديد الملفات
		 */
		upload: () => LocalizedString
		/**
		 * حدد تاريخا
		 */
		selectDate: () => LocalizedString
		/**
		 * ابحث عن عنوان
		 */
		searchAddress: () => LocalizedString
		/**
		 * تاريخ
		 */
		date: () => LocalizedString
		/**
		 * ساعات
		 */
		hours: () => LocalizedString
		/**
		 * دقائق
		 */
		minutes: () => LocalizedString
		/**
		 * السنة 
		 */
		year: () => LocalizedString
		/**
		 * الشهر
		 */
		month: () => LocalizedString
		/**
		 * وسيلة نقل
		 */
		transportMethod: () => LocalizedString
	}
	errors: {
		/**
		 * غير مسموح
		 */
		forbidden: () => LocalizedString
		/**
		 * غير موجود
		 */
		notFound: () => LocalizedString
		/**
		 * خطأ في الخادم
		 */
		internalServerError: () => LocalizedString
		/**
		 * طلب خاطئ
		 */
		badRequest: () => LocalizedString
		/**
		 * الخدمة غير متوفرة
		 */
		serviceUnavailable: () => LocalizedString
		/**
		 * حدث خطأ أثناء تحميل الملف
		 */
		unableToUploadFile: () => LocalizedString
	}
	schema: {
		/**
		 * الاسم الكامل
		 */
		fullname: () => LocalizedString
		/**
		 * البريد الالكتروني
		 */
		email: () => LocalizedString
		/**
		 * كلمة المرور
		 */
		password: () => LocalizedString
		/**
		 * العنوان الفعلي
		 */
		address: () => LocalizedString
		/**
		 * الصورة الرمزية
		 */
		avatar: () => LocalizedString
		/**
		 * رقم هاتف
		 */
		phoneNumber: () => LocalizedString
	}
	validation: {
		/**
		 * الاسم الكامل يجب أن يكون على الأقل {0} أحرف
		 */
		fullname: (arg0: unknown) => LocalizedString
		/**
		 * عنوان البريد الإلكتروني غير صالح
		 */
		email: () => LocalizedString
		/**
		 * يجب أن يكون عنوان {0} حرفًا على الأقل
		 */
		address: (arg0: unknown) => LocalizedString
		/**
		 * يجب أن يكون رقم الهاتف مكونًا من 10 أرقام
		 */
		phoneNumber: () => LocalizedString
		/**
		 * حجم الصورة لا يمكن أن يتجاوز {0} ميجا بايت
		 */
		imageSize: (arg0: unknown) => LocalizedString
		/**
		 * يجب عليك تحميل ملف الصورة
		 */
		invalidImageUpload: () => LocalizedString
		/**
		 * يمكنك تحميل ما يصل إلى {0} ملف
		 */
		maxFilesNumber: (arg0: unknown) => LocalizedString
		/**
		 * يجب أن تكون كلمة المرور مكونة من {0} أحرف على الأقل
		 */
		passwordLength: (arg0: unknown) => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف خاص واحد على الأقل
		 */
		passwordSpecialChar: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على رقم واحد على الأقل
		 */
		passwordNumber: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل
		 */
		passwordUppercase: () => LocalizedString
		/**
		 * يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل
		 */
		passwordLowercase: () => LocalizedString
		/**
		 * لا يمكن أن يتجاوز طول النص {0} حرفًا
		 */
		metaDataText: (arg0: unknown) => LocalizedString
		/**
		 * يجب عليك تحديد تاريخ
		 */
		itemDate: () => LocalizedString
		/**
		 * تحتاج إلى تحديد فئة
		 */
		itemCategory: () => LocalizedString
		/**
		 * عنوان شيء غير صالح
		 */
		invalidItemAddress: () => LocalizedString
	}
	auth: {
		/**
		 * تسجيل الدخول
		 */
		login: () => LocalizedString
		/**
		 * إنشاء حساب
		 */
		signup: () => LocalizedString
		/**
		 * لديك حساب بالفعل؟
		 */
		alreadyHaveAccount: () => LocalizedString
		/**
		 * ليس لديك حساب؟
		 */
		dontHaveAccount: () => LocalizedString
		/**
		 * نسيت كلمة المرور؟
		 */
		forgetPassword: () => LocalizedString
		/**
		 * إرسال الرمز
		 */
		sendTheCode: () => LocalizedString
		/**
		 * إعادة إرسال البريد الإلكتروني
		 */
		resendEmail: () => LocalizedString
		/**
		 * تم إعادة إرسال البريد الإلكتروني بنجاح
		 */
		resendSuccess: () => LocalizedString
		/**
		 * تم إرسال الرمز بنجاح
		 */
		sendSuccess: () => LocalizedString
		/**
		 * تم إعادة تعيين كلمة المرور بنجاح
		 */
		resetPasswordSuccess: () => LocalizedString
		/**
		 * تحقق من الرمز
		 */
		verifyCode: () => LocalizedString
		/**
		 * اكتب البريد الإلكتروني الذي نسيت كلمة المرور الخاصة به
		 */
		lostPasswordEmail: () => LocalizedString
		/**
		 * لقد أرسلنا لك كلمة مرور لمرة واحدة؛ تحقق من صندوق الوارد في بريدك الإلكتروني. ثم اكتب كلمة المرور الجديدة.
		 */
		resetPassword: () => LocalizedString
		/**
		 * تأكيد كلمة المرور الجديدة
		 */
		confirmNewPassword: () => LocalizedString
		/**
		 * لقد أرسلنا لك كلمة مرور للتحقق من بريدك الإلكتروني. تحقق من صندوق الوارد الخاص بك؛ إذا لم يكن موجودًا، تحقق من مجلد البريد العشوائي
		 */
		verificationEmail: () => LocalizedString
		/**
		 * يبدو أن هذا الحساب موجود بالفعل
		 */
		acounntAlreadyExist: () => LocalizedString
		/**
		 * يبدو أن هذا الحساب غير موجود
		 */
		accountDoesNotExist: () => LocalizedString
		/**
		 * كلمة المرور غير صحيحة
		 */
		passwordIncorrect: () => LocalizedString
		/**
		 * الرمز غير صحيح
		 */
		incorrectCode: () => LocalizedString
		/**
		 * الرمز منتهي الصلاحية، حاول إعادة الإرسال
		 */
		expiredCode: () => LocalizedString
		/**
		 * تسجيل الخروج
		 */
		logout: () => LocalizedString
	}
	navbar: {
		/**
		 * اختر اللغة
		 */
		selectLanguage: () => LocalizedString
		/**
		 * المنشورات
		 */
		posts: () => LocalizedString
		/**
		 * العلاقات
		 */
		connections: () => LocalizedString
	}
	home: {
		/**
		 * اجد اشيائك المفقودة بدون عناء
		 */
		title: () => LocalizedString
		/**
		 * يعيد لك نظام المطابقة الذكي الخاص بنا العثور على العناصر المفقودة تلقائيًا. نظام آمن وفعال ومصمم للجميع.
		 */
		description: () => LocalizedString
		/**
		 * ابحث عن أشيائك
		 */
		findYourThings: () => LocalizedString
	}
	profile: {
		/**
		 * يمكنك تغيير اسمك الكامل
		 */
		fullnameChange: () => LocalizedString
		/**
		 * تم تغيير الاسم بنجاح
		 */
		fullnameChangeSuccess: () => LocalizedString
		/**
		 * يجب عليك تحديد عنوانك قبل إنشاء منشور. تأكد من تحديد العنوان الكامل مع الرمز البريدي
		 */
		addressChange: () => LocalizedString
		/**
		 * تم تغيير العنوان بنجاح
		 */
		addressChangeSuccess: () => LocalizedString
		/**
		 * يمكنك تغيير الصورة الرمزية الخاصة بك
		 */
		avatarChange: () => LocalizedString
		/**
		 * تم تغيير الصورة الرمزية بنجاح
		 */
		avatarChangeSuccess: () => LocalizedString
		/**
		 * يمكنك تسجيل الخروج. سيؤدي هذا إلى إنهاء جلسة التصفح الخاصة بك
		 */
		logout: () => LocalizedString
		/**
		 * يجب عليك تحديد رقم هاتفك قبل إنشاء المنشور
		 */
		phoneNumberChange: () => LocalizedString
		/**
		 * تم تغيير رقم الهاتف بنجاح
		 */
		phoneNumberChangeSuccess: () => LocalizedString
	}
	posts: {
		/**
		 * منشور جديد
		 */
		newPost: () => LocalizedString
		/**
		 * العودة إلى الفئات
		 */
		returnCategories: () => LocalizedString
		/**
		 * مفقود
		 */
		lost: () => LocalizedString
		/**
		 * موجود
		 */
		found: () => LocalizedString
		/**
		 * اختر نوع الشيء
		 */
		selectItemType: () => LocalizedString
		/**
		 * البيانات الوصفية للشيء لها قيم افتراضية. إذا كنت لا تعرف قيمها فلا تقم بتعيينها
		 */
		createDescription: () => LocalizedString
		/**
		 * أين فقدت الشيء؟
		 */
		whereYouLost: () => LocalizedString
		/**
		 * متى فقدت الشيء؟
		 */
		whenYouLost: () => LocalizedString
		/**
		 * متى وجدت الشيء؟
		 */
		whenYouFound: () => LocalizedString
		/**
		 * أين وجدت الشيء؟
		 */
		whereYouFound: () => LocalizedString
		/**
		 * يمكنك كتابة وصف كامل للعنصر المفقود
		 */
		lostItemDescription: () => LocalizedString
		/**
		 * صور تظهر العنصر الخاص بك
		 */
		lostItemImages: () => LocalizedString
		/**
		 * النقل
		 */
		transport: () => LocalizedString
		/**
		 * العنوان
		 */
		address: () => LocalizedString
		/**
		 * نقطة انطلاق النقل
		 */
		transportStart: () => LocalizedString
		/**
		 * نقطة انتهاء النقل
		 */
		transportEnd: () => LocalizedString
		/**
		 * إضافة عنوان إضافي
		 */
		additionalAddress: () => LocalizedString
		/**
		 * نوع
		 */
		postType: () => LocalizedString
		/**
		 * الحالة
		 */
		postState: () => LocalizedString
		/**
		 * الفئة
		 */
		itemCategory: () => LocalizedString
		/**
		 * المزيد من المعلومات
		 */
		seeInfo: () => LocalizedString
	}
	postStates: {
		/**
		 * عاطل
		 */
		idle: () => LocalizedString
		/**
		 * مطابقة
		 */
		matched: () => LocalizedString
	}
}

export type Formatters = {}
